### ISSUE TITLE
vagrant, relation "User" does not exist

### ISSUE THREAD

**Issue by Hans-Maulwurf** [crestify/crestify#29]
Well, i'm really struggling with getting crestify (within vagrant) running. I managed to get over the mail-sending-error by editing the override.py and inserting a working smtp-server. But now it seems like the database was not set up correctly? Is there something wrong with the fabfile? The error occurs when trying to register a new user.

`ERROR:crestify:Exception on /register [POST]
Traceback (most recent call last):
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask_cors.py", line 272, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask_security/decorators.py", line 225, in wrapper
    return f(*args, **kwargs)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask_security/views.py", line 116, in register
    if form.validate_on_submit():
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask_wtf/form.py", line 166, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 200, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 220, in _run_validation_chain
    validator(form, self)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask_security/forms.py", line 78, in unique_user_email
    if _datastore.get_user(field.data) is not None:
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/flask_security/datastore.py", line 191, in get_user
    rv = self.user_model.query.filter(query).first()
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2367, in first
    ret = list(self[0:1])
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
    return list(res)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2453, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "User" does not exist
LINE 2: FROM "User" 
             ^
 'SELECT "User".id AS "User_id", "User".email AS "User_email", "User".password AS "User_password", "User".first_name AS "User_first_name", "User".last_name AS "User_last_name", "User".active AS "User_active", "User".confirmed_at AS "User_confirmed_at", "User".bookmarks_per_page AS "User_bookmarks_per_page", "User".api_key AS "User_api_key" \nFROM "User" \nWHERE "User".email ILIKE %(email_1)s \n LIMIT %(param_1)s' {'email...`

**Comment by satyanash** [comment]
```
relation "User" does not exist
```
It looks like the fabfile doesn't run the migrations. You need to ssh into the vm and run the migrations manually.

```
vagrant ssh
sudo su crestify
cd /home/crestify
source crestifyenv/bin/activate
cd crestify
honcho run python main.py db upgrade
deactivate
exit
exit
```

The registration endpoint may not `200 OK`  but if you `psql -U crestify crestify` into the postgres instance you should see the created user.

**Comment by Hans-Maulwurf** [comment]
Well this part "noncho run python...." in not in the fabfile. It's only mentioned in the install.md. Could you add it to the fabfile?

**Comment by dhamaniasad** [comment]
The fabfile now runs the migrations, and you won't need to SSH into the vagrant box and run them manually. The fix is in the master branch now.
