### ISSUE TITLE
Raven is not configured error when installing

### ISSUE THREAD

**Issue by kaneru** [crestify/crestify#4]
When setting up the database I get this error:

```shell
honcho run python main.py db upgrade
```

```
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from crestify.views.manager import *
  File "/Users/kaneru/crestify/crestify/views/manager.py", line 8, in <module>
    from crestify.services import bookmark, tab
  File "/Users/kaneru/crestify/crestify/services/bookmark.py", line 4, in <module>
    from crestify.services import archive
  File "/Users/kaneru/crestify/crestify/services/archive.py", line 6, in <module>
    from crestify.tasks import celery
  File "/Users/kaneru/crestify/crestify/tasks/__init__.py", line 3, in <module>
    from celery import Celery
  File "/Users/kaneru/crestify/venv/lib/python2.7/site-packages/celery/__init__.py", line 130, in <module>
    from celery import five
  File "/Users/kaneru/crestify/venv/lib/python2.7/site-packages/celery/five.py", line 149, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
  File "/Users/kaneru/crestify/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 19, in <module>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name _uuid_generate_random
```

**Comment by dhamaniasad** [comment]
I'll have a look into this and see where the problem stems from. Hoping to
push a fix soon.

**Comment by trifle** [comment]
This is a bug in the kombu version defined in requirements.txt.
If you install the newest kombu and celery versions (`pip install -U celery`), you should be good to go.

**Comment by kaneru** [comment]
@trifle thank you! I was able to proceed further with the installation. But still I get this error:

```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 98, in upgrade
    command.upgrade(config, revision, sql = sql, tag = tag)
  File "/usr/local/lib/python2.7/site-packages/alembic/command.py", line 129, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/site-packages/alembic/script.py", line 208, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/site-packages/alembic/util.py", line 230, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/site-packages/alembic/compat.py", line 63, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "migrations/env.py", line 57, in run_migrations_online
    connection = engine.connect()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1778, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 60, in __init__
    self.__connection = connection or engine.raw_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1847, in raw_connection
    return self.pool.unique_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 280, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 644, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 285, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 411, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 538, in __connect
    connection = self.__pool._creator()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 96, in connect
    connection_invalidated=invalidated
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (OperationalError) FATAL:  role "crestify" does not exist
 None None
```

I suppose I did't create datatable with the name `crestify`. How do I create it in a correct way? 

Thanks in advance.

**Comment by dhamaniasad** [comment]
The `deploy.md` file has instructions for creating the database. Please refer to it and if you run into any more issues, I'm happy to help :)

**Comment by dhamaniasad** [comment]
According to the default config, you need to create a database `crestify` with a user `crestify` password `crestify`. I'll add instructions for this.

**Comment by dhamaniasad** [comment]
Moved to #10.
